spring.application.name=TaskManagementProject

#MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:6532/task_management
spring.datasource.password=Yogesh@97
spring.datasource.username=root

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=taskmanagement246@gmail.com
spring.mail.password=lsii wpaf ygqt bgmm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true